### ISSUE TITLE
SSH CONNECTION REFUSED

### ISSUE THREAD

**Issue by ghost** [gx0c/termux-bot#1]
;-;

**Comment by qxb3** [comment]
Are you sure you got your discord bot token right?

**Comment by ghost** [comment]
> Are you sure you got your discord bot token right?

Yeah it's my friend's bot token

**Comment by qxb3** [comment]
> > Are you sure you got your discord bot token right?
> 
> Yeah it's my friend's bot token

What is the error says? Is it for the ssh or the discord bot?
